# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages


jobs:
  include:
  - r: 3.2
  - r: 3.3
  - stage: full
    os: osx
  - r: oldrel
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
  - r: devel

matrix:
  fast_finish: true
